# Generated by Django 3.0.4 on 2020-04-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the product')),
                ('description', models.CharField(max_length=255, verbose_name='Describe the product')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
