# Generated by Django 3.0.4 on 2020-04-02 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ImageField(max_length=255, upload_to='', verbose_name='Describe la imagen')),
                ('image', models.ImageField(upload_to='imagenes_producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_imagen', to='products.Product')),
            ],
        ),
    ]
