# Generated by Django 3.0.4 on 2020-04-02 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_imageproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Describe la imagen'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('datos_payu', models.CharField(max_length=600)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_carrito', to='products.Product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
